		
		TERM PROJECT STEPS // EE400 // RETINA ROBOTICS // Middle East Technical University
		
	1) 	Decide the Meeting Hours and Days (for in-company meetings)
	
	2) 	Choose a Chief Executive of the Organisation (CEO) who is going to head the gatherings
	
	3) 	Have All Projects Discussed and Examined
	
	4) 	List the Projects 'Posivite and Negaive Sides'
	
	5) 	Select individual persons for each project to find more information
	
	6) 	Discuss what is done with the Advisor Professor
	
	7) 	Throw and/or Find some pulp-based, not so-developed algorithms on each project
	
	8) 	Decision on choosing the Project
	
	9) 	Do a wide-research on the chosen Project
	
	10)	Develop an User Interface (UI) for a basic/fundamental start
	
	11) Develop and try to implement the algorithms found previous steps during the decision of choice of the Project
	
	12)	If none works, try to find other ways to solve the Problem(!)
	
	13)	When the UI is close to be done, make job-division between the Company Workers
	
	14) In this step, each individual will be seperated into different "departments" so each step will take no longer than before anymore
	
	15) Start making small tests for the sight of the Advances and Enhancements in the progress
	
	16) Decide on a "Meeting Day" (!)
	
	17) A long meeting that all processes and progresses are going to be discussed
	
	17) TESTS before the Semester